// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayfjrkjwbljkecqfsrxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5Zmpya2p3Ymxqa2VjcWZzcnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MjEwODQsImV4cCI6MjA3NTQ5NzA4NH0.CGZC8uSYJIf9uWBQypsAcL1AA_TnARDRlh59o5x4jpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});